### ISSUE TITLE
Progress Checklist

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#441]
Cessna 172S Normal Operation Checklist

Based on [West House Airport’s](https://www.google.com/url?q=https://www.westhoustonairport.com/aviationlinks/pdfs/checklist-cessna-172S-analog.pdf&sa=D&source=editors&ust=1711035879655282&usg=AOvVaw3KXmMjE_pjW8cTfbX43u34)

BEFORE STARTING ENGINE
- [ ] Preflight Inspection COMPLETE
- [ ] Passenger Briefing COMPLETE
- [ ] Seats & Seat Belts ADJUST & LOCK (ASSURE INERTIAL REEL LOCKING)
- [ ] Brakes TEST & SET
- [ ] Circuit Breakers CHECK ENGAGED (IN)
- [ ] Electrical Equipment OFF

WARNING
Avionics Power must be "OFF" during Engine Start to prevent damage to Avionics.

- [ ] Avionics Power Switch OFF
- [ ] Fuel Selector Valve BOTH
- [ ] Fuel Shut-Off Valve ON (PUSH FULL IN)

STARTING ENGINE -- Normal With Battery
- [ ] Throttle OPEN 1/4 INCH
- [ ] Mixture IDLE CUT-OFF
- [ ] Propeller & Blast Areas CLEAR VISUAL & (VERBAL WARNING)
- [ ] External Power (If Used) CONNECT
- [ ] Master Switch ON
- [ ] Flashing Beacon ON

NOTE
IF ENGINE IS WARM, OMIT PRIMING PROCEDURE of Step 7 & 8

- [ ] Aux. Fuel Pump Switch ON
- [ ] Mixture ADVANCE TO OBTAIN 3 to 5 GHP FUEL FLOW, THEN QUICKLY RETURN TO IDLE CUT-OFF POSITION
- [ ] Aux. Fuel Pump OFF
- [ ] Ignition Switch START (RELEASE WHEN ENGINE STARTS)
- [ ] Mixture ADVANCE SMOOTHLY to RICH WHEN ENGINE FIRES
- [ ] Throttle 1100 to 1200 RPM
- [ ] Oil Pressure CHECK (Must Start UP within 30 Seconds)
- [ ] Ammeter CHECK

WARNING
Ammeter should indicate some charge immediately after engine starts.

BEFORE TAXI
- [ ] Flashing Beacon ON
- [ ] Nav Lights (If Dark or Near Sunset) ON
- [ ] Avionics Power Switch ON
- [ ] Radios ON, SET FREQUENCIES, ADJUST VOLUME
- [ ] Transponder STANDBY
- [ ] Wing Flaps UP
- [ ] TAXIING
- [ ] Brakes TEST Before Taxiing More Than The Length of The Fuselage.
- [ ] Throttle USE MINIMUM POWER, Adjust As Needed. Use Brakes Only to SUPPLEMENT Power Adjustments.
- [ ] BEFORE TAKEOFF

Parking Brake SET
- [ ] Throttle 1100 to 1200 RPM
- [ ] Seat Backs UPRIGHT POSITION
- [ ] Seats & Seat Belts CHECK SECURE
- [ ] Cabin Doors CLOSED & LOCKED
- [ ] Flight Controls MOVE FREE IN PROPER DIRECTION
- [ ] Flight Instruments CHECK & SET
- [ ] Fuel Quantity CHECK
- [ ] Mixture RICH
- [ ] Fuel Selector Valve BOTH
- [ ] Elevator Trim SET FOR TAKEOFF
- [ ] BEFORE TAKEOFF (CONTINUATION)

- [ ] 
- [ ] Throttle 1,800 RPM
- [ ] Magnetos CHECK
- [ ] [RPM Drop should not exceed 150 RPM on a single magneto, or 50 RPM difference between the magnetos.]
- [ ] Vacuum Gauge CHECK
- [ ] Engine Instruments & Ammeter CHECK
- [ ] Throttle 1100 to 1200 RPM
- [ ] Throttle Friction Lock ADJUST
- [ ] Taxi Light ON
- [ ] Strobe Light ON
- [ ] Radios & AvionicsS SET FREQUENCIES & VOLUME
- [ ] Transponder SET ALTITUDE & CORRECT CODE
- [ ] Auto-Pilot OFF
- [ ] Wing Flaps SET FOR TAKEOFF
- [ ] Brakes RELEASE
- [ ] THE SCHOOL RECOMMENDS using a TAXI LIGHT or LANDING LIGHT when operating in or within one mile of the Airport Traffic Pattern to aid others in seeing you.

TAKEOFF - Normal
- [ ] Flaps 0° to 10°
- [ ] Throttle 3. Mixture FULL OPEN RICH (Above 3,000 MSL, LEAN to MAXIMUM RPM
- [ ] Elevator Control LIFT NOSE (ROTATE) at 55 Kts 70 to 80 Kts (Recommend VY 74 Kts) 5. Climb Airspeed
- [ ] TAKEOFF - Short Field
- [ ] Flaps 10°
- [ ] Brakes APPLY
- [ ] Throttle FULL OPEN (Smoothly)
- [ ] Mixture RICH (Above 3,000 MSL, LEAN to MAXIMUM RPM)
- [ ] Brakes RELEASE
- [ ] Elevator Control SLIGHTLY NOSE HIGH
- [ ] Flaps 7. Climb Airspeed UP After Reaching 60 Kts. 56 Kts UNTIL ALL OBSTACLES CLEARED

ENROUTE CLIMB
- [ ] Landing & Taxi Lights OFF
- [ ] Throttle FULL OPEN
- [ ] Mixture RICH (Above 3,000 MSL, LEAN to MAX. RPM)
- [ ] If maximum performance climb is necessary, consult Pilots Operating Handbook, Section 5, RATE-OF-CLIMB Chart.
- [ ] Airspeed 70 to 85 Kts (Recommend Vý 74 Kts)

CRUISE
- [ ] Power ....... 65% (Usually obtained by 2,300 to 2,400 RPM) ADJUST
- [ ] Elevator Trim
- [ ] Mixture LEAN to BEST POWER SETTING (Excessive Leaning May Damage Engine Severely.)
- [ ] DESCENT
- [ ] Fuel Selector Valve BOTH
- [ ] Power AS DESIRED

[WARNING] Reducing power below 1500 RPM without reducing airspeed may cause excessive engine cooling.

Mixture For Idle Power ADJUST for SMOOTH OPERATION FULL RICH

BEFORE LANDING (Mid Part of Down-Wind Leg)or Before)
- [ ] Taxi Light ON
- [ ] Seat Belts & Shoulder Harness SECURE
- [ ] Seat Backs MOST UPRIGHT POSITION
- [ ] Fuel Selector Valve BOTH
- [ ] Mixture RICH
- [ ] Auto-Pilot. OFF
- [ ] Radios (Frequencies, Volume) SET

LANDING -- Normal
- [ ] Airspeed 65 to 70 Kts
- [ ] Flaps AS DESIRED [0° to 10° below 110 Kts]
- [ ] Airspeed Minimum [10+ below 85 Kts] 0 62 Kts with Flaps 30
- [ ] Touchdown MAIN WHEELS FIRST
- [ ] Landing Roll ALLOW NOSE WHEEL to LOWER GENTLY
- [ ] Brakes MINIMUM REQUIRED [Aerodynamic Braking recommended to supplement wheel brakes]
- [ ] LANDING - Short Field
- [ ] Airspeed 65 Kts (With Flaps 0)
- [ ] Flaps EXTEND AS NEEDED UNTIL 30
- [ ] Airspeed On Final Approach 61 Kts [Until Flare-Out]
- [ ] Power REDUCE TO IDLE When Obstacles Cleared
- [ ] Touchdown MAIN WHEELS FIRST
- [ ] Brakes [When Firmly On Ground] APPLY HEAVILY
- [ ] Flaps *** DO NOT SKID TIRES *** RETRACT if having difficulty with traction
